const test=require('node:test'); const assert=require('node:assert/strict');
const {executarIsolado,removerAmbiente}=require('./helpers/isolated');

test('PIX aprovado renova uma vez; duplicado, divergente e pendente nao renovam',()=>{
 const r=executarIsolado(`(async()=>{const db=require('./database/sqlite');await db.ready;const run=(s,p=[])=>new Promise((ok,no)=>db.run(s,p,function(e){e?no(e):ok({id:this.lastID,changes:this.changes})}));const get=(s,p=[])=>new Promise((ok,no)=>db.get(s,p,(e,x)=>e?no(e):ok(x)));await run("INSERT INTO configuracoes (chave,valor) VALUES ('pixProvedor','mercado_pago'),('mercadoPagoAccessToken','token')");const c=await run("INSERT INTO clientes (nome,telefone,plano,diasContrato,valorPlano,dataVencimento,vencimento,status) VALUES (?,?,?,?,?,?,?,?)",['Teste','5511999999999','Mensal',30,'35,00','2026-07-30T23:59','2026-07-30','ativo']);for(const x of [['ref-ok','pay-ok'],['ref-wrong','pay-wrong'],['ref-pending','pay-pending']])await run("INSERT INTO cobrancas_pix (referencia,provedor,provedorPagamentoId,clienteId,plano,diasContrato,valorPlano,valorTotal,status) VALUES (?,'mercado_pago',?,?,?,?,?,?,'pending')",[x[0],x[1],c.id,'Mensal',30,'35,00','35,00']);const respostas={'pay-ok':{id:'pay-ok',status:'approved',external_reference:'ref-ok',transaction_amount:35,date_approved:'2026-07-24T12:00:00Z'},'pay-wrong':{id:'pay-wrong',status:'approved',external_reference:'ref-wrong',transaction_amount:34,date_approved:'2026-07-24T12:00:00Z'},'pay-pending':{id:'pay-pending',status:'pending',external_reference:'ref-pending',transaction_amount:35}};global.fetch=async u=>({ok:true,json:async()=>respostas[decodeURIComponent(String(u).split('/').pop())],text:async()=>''});const mp=require('./services/mercadoPagoService');const ok=await mp.processarPagamentoMercadoPago('pay-ok');const dup=await mp.processarPagamentoMercadoPago('pay-ok');let errado=false;try{await mp.processarPagamentoMercadoPago('pay-wrong')}catch(_){errado=true}const pend=await mp.processarPagamentoMercadoPago('pay-pending');const total=await get('SELECT COUNT(*) total FROM cliente_pagamentos');const st=await get("SELECT status FROM cobrancas_pix WHERE referencia='ref-wrong'");process.stdout.write(JSON.stringify({ok:ok.aprovado,dup:dup.duplicado,errado,pend:pend.pendente,total:total.total,status:st.status}));db.close()})().catch(e=>{console.error(e);process.exit(1)})`);
 try{assert.deepEqual(JSON.parse(r.stdout),{ok:true,dup:true,errado:true,pend:true,total:1,status:'valor_divergente'})}finally{removerAmbiente(r.ambiente)}
});

test('vencimento manual e automatico montam a mesma mensagem',()=>{
 const r=executarIsolado(`(async()=>{const {montarMensagemRenovacao}=require('./services/renovacaoAutomatica');const c={nome:'Carlos',plano:'mensal',vencimento:'2026-07-30',dataVencimento:'2026-07-30T23:59'};process.stdout.write(JSON.stringify([await montarMensagemRenovacao(c),await montarMensagemRenovacao(c)]))})().catch(e=>{console.error(e);process.exit(1)})`);
 try{const [a,b]=JSON.parse(r.stdout);assert.equal(a,b);assert.match(a,/Carlos/);assert.match(a,/mensal/i);assert.match(a,/\d+ dia/)}finally{removerAmbiente(r.ambiente)}
});

test('PayPal cria cobranca BRL e renova uma unica vez apos captura concluida',()=>{
 const r=executarIsolado(`(async()=>{const db=require('./database/sqlite');await db.ready;const run=(s,p=[])=>new Promise((ok,no)=>db.run(s,p,function(e){e?no(e):ok({id:this.lastID,changes:this.changes})}));const get=(s,p=[])=>new Promise((ok,no)=>db.get(s,p,(e,x)=>e?no(e):ok(x)));await run("INSERT INTO configuracoes (chave,valor) VALUES ('paypalAtivo','1'),('paypalAmbiente','sandbox'),('paypalClientId','client'),('paypalClientSecret','secret'),('paypalRetornoUrl','https://cliente.example.com')");const c=await run("INSERT INTO clientes (nome,telefone,plano,diasContrato,valorPlano,dataVencimento,vencimento,status) VALUES (?,?,?,?,?,?,?,?)",['Cliente Exterior','5511999999999','Mensal',30,'35,00','2026-07-30T23:59','2026-07-30','ativo']);let referencia='';global.fetch=async(u,o={})=>{u=String(u);if(u.endsWith('/v1/oauth2/token'))return{ok:true,json:async()=>({access_token:'token'})};if(u.endsWith('/v2/checkout/orders')&&o.method==='POST'){const b=JSON.parse(o.body);referencia=b.purchase_units[0].custom_id;if(b.purchase_units[0].amount.currency_code!=='BRL'||b.purchase_units[0].amount.value!=='35.00')throw new Error('moeda ou valor incorreto');return{ok:true,json:async()=>({id:'ORDER123',status:'CREATED',links:[{rel:'approve',href:'https://paypal.test/ORDER123'}]})}}if(u.endsWith('/v2/checkout/orders/ORDER123'))return{ok:true,json:async()=>({id:'ORDER123',status:'COMPLETED',purchase_units:[{custom_id:referencia,amount:{currency_code:'BRL',value:'35.00'},payments:{captures:[{id:'CAPTURE1',status:'COMPLETED',amount:{currency_code:'BRL',value:'35.00'}}]}}]})};throw new Error('URL inesperada '+u)};const pp=require('./services/paypalService');const criada=await pp.criarCobrancaPayPal({nome:'Mensal',valor:'35,00',valorNumero:35,dias:30},{clienteId:c.id,plano:'Mensal',diasContrato:30,valorPlano:'35,00'});const ok=await pp.processarOrdemPayPal(criada.ordemId);const dup=await pp.processarOrdemPayPal(criada.ordemId);const total=await get('SELECT COUNT(*) total FROM cliente_pagamentos');const cobranca=await get("SELECT provedor,status FROM cobrancas_pix WHERE referencia=?",[referencia]);process.stdout.write(JSON.stringify({link:criada.link,ok:ok.aprovado,dup:dup.duplicado,total:total.total,provedor:cobranca.provedor,status:cobranca.status}));db.close()})().catch(e=>{console.error(e);process.exit(1)})`);
 try{assert.deepEqual(JSON.parse(r.stdout),{link:'https://paypal.test/ORDER123',ok:true,dup:true,total:1,provedor:'paypal',status:'aprovado'})}finally{removerAmbiente(r.ambiente)}
});
