const test=require('node:test'); const assert=require('node:assert/strict');
const fs=require('fs'); const path=require('path');
const {executarIsolado,removerAmbiente,repoRoot}=require('./helpers/isolated');

test('HTML desativa atalhos do LastPass em todos os campos e formularios',()=>{const s=require('../services/securityService');const html=s.desativarAtalhosGerenciadorSenhas('<html><head></head><body><form><input type="password" data-autofill-empty="true"><textarea></textarea><select></select></form></body></html>');assert.equal((html.match(/data-lpignore="true"/g)||[]).length,4);assert.match(html,/julian-play-password-manager-style/);assert.match(html,/julian-play-password-manager-control/);assert.match(html,/campo-segredo-manual/);assert.match(html,/el\.type = 'text'/);assert.match(html,/data-1p-ignore/);assert.match(html,/data-bwignore/);assert.match(html,/usuarioDigitou/);assert.match(html,/setInterval\(\(\) => limpar\(\), 250\)/);assert.match(html,/clearInterval\(vigilancia\)/);assert.match(html,/MutationObserver/)});

test('pagina de login preserva preenchimento automatico',()=>{const s=require('../services/securityService');const html=s.desativarAtalhosGerenciadorSenhas('<form method="post" action="/login"><input name="usuario" autocomplete="username"><input type="password" name="senha" autocomplete="current-password"></form>');assert.doesNotMatch(html.match(/<form[\s\S]*?<\/form>/)[0],/data-lpignore/);assert.match(html,/autocomplete="username"/);assert.match(html,/autocomplete="current-password"/)});

test('CAPTCHA assinado aceita resposta correta e rejeita alteracao',()=>{const r=executarIsolado(`const s=require('./services/securityService');const c=s.criarCaptcha();const partes=c.pergunta.split(' ');const resposta=Number(partes[0])+Number(partes[2]);process.stdout.write(JSON.stringify([s.validarCaptcha(c.desafio,resposta),s.validarCaptcha(c.desafio,resposta+1),s.validarCaptcha(c.desafio+'x',resposta)]))`);try{assert.deepEqual(JSON.parse(r.stdout),[true,false,false])}finally{removerAmbiente(r.ambiente)}});

test('CSRF injeta token, bloqueia POST invalido e permite logout seguro',()=>{const r=executarIsolado(`(async()=>{const express=require('express');const s=require('./services/securityService');const app=express();app.use(express.urlencoded({extended:false}));app.use(s.csrfMiddleware({isento:req=>req.path==='/logout'}));app.get('/',(q,p)=>p.send('<form method="post" action="/salvar"></form>'));app.post('/salvar',(q,p)=>p.send('ok'));app.post('/logout',(q,p)=>p.send('saiu'));const server=await new Promise(ok=>{const x=app.listen(0,'127.0.0.1',()=>ok(x))});const base='http://127.0.0.1:'+server.address().port;const get=await fetch(base+'/');const html=await get.text();const cookie=get.headers.get('set-cookie').split(';')[0];const token=html.match(/name="_csrf" value="([a-f0-9]+)"/)[1];const negado=await fetch(base+'/salvar',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:'x=1'});const aceito=await fetch(base+'/salvar',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded','cookie':cookie},body:'_csrf='+token});const logout=await fetch(base+'/logout',{method:'POST'});process.stdout.write(JSON.stringify({injeta:html.includes('_csrf'),negado:negado.status,aceito:aceito.status,logout:logout.status}));await new Promise(ok=>server.close(ok))})().catch(e=>{console.error(e);process.exit(1)})`);try{assert.deepEqual(JSON.parse(r.stdout),{injeta:true,negado:403,aceito:200,logout:200})}finally{removerAmbiente(r.ambiente)}});

test('logout revoga imediatamente e sessao persiste no banco',()=>{const r=executarIsolado(`(async()=>{const a=require('./services/authService');const s=await a.criarSessao('admin',{headers:{'user-agent':'teste'},ip:'127.0.0.1'});const req={headers:{cookie:'julian_play_session='+s.token}};const antes=!!(await a.obterSessao(req));delete require.cache[require.resolve('./services/authService')];const recarregado=require('./services/authService');const persistiu=!!(await recarregado.obterSessao(req));await recarregado.encerrarSessao(req);process.stdout.write(JSON.stringify([antes,persistiu,!!(await recarregado.obterSessao(req))]));process.exit(0)})().catch(e=>{console.error(e);process.exit(1)})`);try{assert.deepEqual(JSON.parse(r.stdout),[true,true,false])}finally{removerAmbiente(r.ambiente)}});

test('health externo nao expoe numero nem ultimos contatos do WhatsApp',()=>{const bot=fs.readFileSync(path.join(repoRoot,'bot.js'),'utf8');const inicio=bot.indexOf("app.get('/health'");const fim=bot.indexOf('app.use(protegerPainel)',inicio);const rota=bot.slice(inicio,fim);assert.match(rota,/cf-connecting-ip/);assert.match(rota,/x-forwarded-for/);assert.match(rota,/origemLocal/);const respostaExterna=rota.slice(0,rota.indexOf('res.status(200).json({',rota.indexOf('return res.status(200).json({')+10));assert.doesNotMatch(respostaExterna,/numeroConectado|ultimaMensagemRecebidaDe|ultimoEnvioRoboPara/)});
