name: Sync to Alteracao Repo

on:
  push:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true  # Remove o aviso de depreciação

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Principal
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push para Repositório de Alteração
        env:
          MY_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          
          # Clona o repositório usando a variável de ambiente segura
          git clone "https://${MY_TOKEN}@://github.com" target_repo
          
          # Limpa o conteúdo antigo
          find target_repo -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf {} +
          
          # Copia os novos arquivos e pastas
          find . -mindepth 1 -maxdepth 1 ! -name '.git' ! -name 'target_repo' -exec cp -r {} target_repo/ \;
          
          cd target_repo
          git add -A
          
          if ! git diff-index --quiet HEAD; then
            git commit -m "Sync: Automação espelhada do repositório principal"
            git push origin main
          else
            echo "Nenhuma alteração detectada para sincronizar."
          fi
