name: Git Mirror Sync

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout completo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push mirror para repo destino
        run: |
          set -e

          echo "Configurando git..."
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

          echo "Adicionando remote do repo destino..."
          git remote add mirror https://x-access-token:${{ secrets.SYNC_TOKEN }}@github.com/Kaka2002/alteracao.git

          echo "Fazendo push mirror..."
          git push mirror --mirror